apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: harbor.stfc.ac.uk/isisbusapps/health-check-service@sha256:fb77952d43d44b47b0311f15baffc14d575ea2fe61a205c9c9e11cc933cd459c
  selector:
    matchLabels:
      app: health-check-service
