apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: harbor.stfc.ac.uk/isisbusapps/health-check-service@sha256:a0122111193408d571d424b9484e47d5275e119fc6478392ee3bd95df9dcd081
  selector:
    matchLabels:
      app: health-check-service
