apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: harbor.stfc.ac.uk/isisbusapps/health-check-service@sha256:35f696db404b4609c1ae2ac282b121e7c329567d54bdac362623e19f57f71ca1
  selector:
    matchLabels:
      app: health-check-service
