name: Update Server List

on:
  workflow_call:
  push:
    branches:
      - main
      - AuthenticateHealthCheck

jobs:
  dev-move-servers-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Health Check
        uses: actions/checkout@v6
        with:
          path: health-check-service/

      - name: Checkout gitops
        uses: actions/checkout@v6
        with:
          repository: isisbusapps/gitops
          token: ${{ secrets.WORKFLOW_TOKEN }}
          path: gitops/

      - name: Create branch
        working-directory: gitops/
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b "DEV_UpdateHealthCheckServers"      

      - name: Copy servers.json to gitops
        run: |
          cp health-check-service/dev/servers.json gitops/components/infra/health-check-service/overlays/dev/servers.json

      - name: Commit and push changes
        working-directory: gitops/
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "[CD] Update Health Check Service Dev servers.json"
          git push --set-upstream origin "DEV_UpdateHealthCheckServers"

  trigger_pr:
    runs-on: ubuntu-latest
    needs: dev-move-servers-json
    steps:
      - name: Trigger PR Creation
        uses: isisbusapps/gitops/.github/workflows/create-release-pr.yaml@main
        with:
          branchName: DEV_UpdateHealthCheckServers
          sourceRepo: ${{ github.repository }}
          actor: ${{ github.actor }}